on:
  schedule:
    - cron: '18 */3 * * *'
  push:
    branches: main

name: Scrape and plot wind forecast

jobs:
  render:
    name: Scrape and plot wind forecast
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("curl", "data.table", "XML", "lubridate", "ggplot2", "scales"))'
      - name: Scrape the data
        run: Rscript scrape_weather_data.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'HK weather csv & Wind plot' || echo "No changes to commit"
          git push origin main || echo "No changes to commit"
